name: Publish Boilerplate Package in Maven Central Repository

on:
  pull_request:
    branches:
      - main  # Quando o PR for para a branch 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
#          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Garante o histórico completo

      - name: Ensure clean working directory
        run: git reset --hard && git clean -fdx

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3 # v4.0.0

      - name: Give execute permission to gradlew
        run: chmod +x ./gradlew  # Garantindo permissão de execução para o gradlew
      # Incrementar patch e gerar snapshot
      - name: Build with Gradle
        run: bash ./scripts/reckon-auto-versioning

      # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
      # the publishing section of your build.gradle
#      - name: Set up Maven Central Repository
#        uses: actions/setup-java@v4
#        with:
#          java-version: '21'
#          distribution: 'temurin'
#          server-id: central
#          server-username: MAVEN_USERNAME
#          server-password: MAVEN_PASSWORD
#      - name: Import GPG Key
#        run: |
#          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
#        env:
#          GPG_PRIVATE_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
        run: ./gradlew publish