name: Publish Boilerplate Package in Maven Central Repository

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml

      - name: Determine version scope
        run: bash ./scripts/reckon-auto-versioning

#      - name: Set up Git Credentials
#        run: |
#          git config --global user.name "${{ github.actor }}"
#          git config --global user.email "actions@github.com"
#          git config --global credential.helper store
#          echo "https://${{ secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials

      - name: Publish to GitHub Packages
        run: ./gradlew publish reckonTagCreate -Preckon.scope=$SCOPE -Preckon.stage=beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}

      - name: Push tag
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}


        
