name: Publish Boilerplate Package in Maven Central Repository

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml

      - name: Determine version scope
        run: bash ./scripts/reckon-auto-versioning

      - name: Publish to GitHub Packages
        run: echo "Actor ${{ github.actor }}"

      - name: Publish to GitHub Packages
        run: |          
          ./gradlew publish reckonTagCreate -Preckon.scope=$SCOPE -Preckon.stage=beta \
          -Dorg.ajoberstar.grgit.auth.username=${{ github.actor }}
          -Dorg.ajoberstar.grgit.auth.password=${{ secrets.GITHUB_TOKEN }}
        env:
          GRGIT_USER: ${{ secrets.GITHUB_TOKEN }}


        
