name: Publish Boilerplate Package in Maven Central Repository

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
#          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Set execute permissions for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: bash ./scripts/reckon-auto-versioning
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
      # the publishing section of your build.gradle
#      - name: Set up Maven Central Repository
#        uses: actions/setup-java@v4
#        with:
#          java-version: '21'
#          distribution: 'temurin'
#          server-id: central
#          server-username: MAVEN_USERNAME
#          server-password: MAVEN_PASSWORD
#      - name: Import GPG Key
#        run: |
#          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
#        env:
#          GPG_PRIVATE_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
        run: ./gradlew publish