name: Publish Boilerplate Package in Maven Central Repository

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml

      - name: Determine version scope
        run: bash ./scripts/reckon-auto-versioning

      - name: Current Tag
        run: |
          git fetch --tags
          git tag

      - name: Publish to GitHub Packages
        run: ./gradlew clean publish -Preckon.scope=$SCOPE -Preckon.stage=beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}


        
