name: Publish Boilerplate Package in Maven Central Repository

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          server-id: github

      - name: Download Tags Locally
        run: |
          git fetch --tags   

      # Verifica se as tags foram baixadas corretamente
      - name: List tags
        run: git tag -l  # Isso lista todas as tags

      - name: Fetch complete history
        run: |
          git fetch --unshallow
          git fetch --tags

      # Instala semantic-release
      - name: Install semantic-release
        run: |
          npm init -y
          npm install -g semantic-release @semantic-release/git @semantic-release/github @semantic-release/changelog

      # Executa o semantic-release para gerar a versão beta
      - name: Run semantic-release to determine version
        id: semantic_release
        run: |
          VERSION=$(npx semantic-release --dry-run --branches develop | grep 'nextRelease' -A 1 | tail -n 1 | sed 's/.*"\(.*\)"/\1/')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Exibe a versão calculada pelo semantic-release
      - name: Show determined version
        run:
          echo "Calculated version: $VERSION"

      - name: Publish to GitHub Packages
        run: ./gradlew clean publish reckonTagPush -Preckon.version=$VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}