name: Publish Boilerplate Package in Maven Central Repository

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          server-id: github

      - name: Download Tags Locally
        run: |
          git fetch --tags   

      # Verifica se as tags foram baixadas corretamente
      - name: List tags
        run: git tag -l  # Isso lista todas as tags

      - name: Fetch complete history
        run: |
          git fetch --unshallow
          git fetch --tags

      - name: Set up Node.js and Install release Please
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: |
          npm init -y
          npm install
          npm install --save-dev release-please

      # 4. Gerar versão Release Candidate (RC)
      - name: Generate RC Version
        run: |
          npx release-please github-release --repo-url https://github.com/${{ github.repository }} --release-type 'beta' --prerelease --token ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Packages
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "Determined version: $VERSION"
          ./gradlew clean publish -Pversion=$VERSION
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}