name: Publish Boilerplate Package in Maven Central Repository

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          server-id: github

      - name: Download Tags Locally
        run: |
          git fetch --tags   

      # Verifica se as tags foram baixadas corretamente
      - name: List tags
        run: git tag -l  # Isso lista todas as tags

      - name: Fetch complete history
        run: |
          git fetch --unshallow
          git fetch --tags

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm init -y          
          npm install lerna -g          
          npx lerna init          
          npm install

      - name: Configure Lerna for Conventional Commits
        run: |
          # Atualiza lerna.json para usar versionamento baseado em Conventional Commits
          npx json -I -f lerna.json -e \
            'this.command = this.command || {}; this.command.version = this.command.version || {}; this.command.version.conventionalCommits = true'

      - name: Fetch complete history and tags
        run: |
          git fetch --unshallow
          git fetch --tags

      - name: Run Lerna versioning
        id: lerna_version
        run: |
          # Calcula a versão baseada em Conventional Commits
          npx lerna version --conventional-commits --yes --no-push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Packages
        run: |
          VERSION=$(node -p "require('./lerna.json').version")
          echo "Determined version: $VERSION"
          ./gradlew clean publish reckonTagPush -Preckon.version=$VERSION -Preckon.stage=beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}