name: Publish Boilerplate Package in Maven Central Repository

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          server-id: github

      - name: Download Tags Locally
        run: |
          git fetch --tags   

      # Verifica se as tags foram baixadas corretamente
      - name: List tags
        run: git tag -l  # Isso lista todas as tags

      - name: Fetch complete history
        run: |
          git fetch --unshallow
          git fetch --tags

      - name: Determine version scope
        run: bash ./scripts/reckon-auto-versioning

      - name: Publish to GitHub Packages
        run: ./gradlew clean publish reckonTagPush -Preckon.scope=$SCOPE -Preckon.stage=beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}