name: Publish Boilerplate Package in Maven Central Repository

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          server-id: github

      - name: Determine version scope
        run: bash ./scripts/reckon-auto-versioning

      - name: Current Tag
        run: |
          git fetch --tags   

      - name: Fetch complete history
        run: |
          git fetch --unshallow
          git fetch --tags

      - name: Publish to GitHub Packages
        run: ./gradlew clean publish reckonTagPush -Preckon.scope=$SCOPE -Preckon.stage=final
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}


      - name: Install Conventional Changelog
        run: npm install -g conventional-changelog-cli

      - name: Configure Git Author
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate Changelog
        run: |
          git fetch origin
          npx conventional-changelog -p angular -i CHANGELOG.md -s -r 0
          git add CHANGELOG.md
          git commit -m "docs: update changelog"
          git push origin main