name: Publish Boilerplate Package in Maven Central Repository

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          server-id: github

      - name: Current Tag
        run: |
          git fetch --tags

      - name: Fetch complete history
        run: |
          git fetch --unshallow
          git fetch --tags              

      - name: Publish to GitHub Packages
        run: |
          VERSION=$(npx git-semver-tags --rc | sort -V | tail -n 1)
          echo "Determined version: $VERSION"
          ./gradlew clean publish reckonTagPush -Preckon.version=$VERSION -Preckon.stage=rc

      - name: Publish to GitHub Packages
        run: ./gradlew clean publish reckonTagPush -Preckon.scope=$SCOPE -Preckon.stage=rc
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}