name: Publish Boilerplate Package in Maven Central Repository

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      actions: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          server-id: github

      - name: Current Tag
        run: |
          git fetch --tags

      - name: Fetch complete history
        run: |
          git fetch --unshallow
          git fetch --tags              

      - name: Set up Node.js and Install Standard Version
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: |
          npm init -y
          npm install
          npm install --save-dev semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github

      # 6. Gerar nova versão beta com `standard-version`
      - name: Bump Beta Version
        run: |
          VERSION=$(npx semantic-release)
          echo "Determined version: $VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GitHub Packages
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "Determined version: $VERSION"
          ./gradlew clean publish -Pversion=$VERSION
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
